spring.application.name=access-management-service
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.profiles.active=dev